### ISSUE TITLE
Can't update ngrok binary

### ISSUE THREAD

**Issue by Wilson159** [philnash/ngrok-for-vscode#29]
I've tried so many things to get ngrok working through VSCode for a python API...

I installed the extensions and its giving me `Can't update ngrok binary. The extension may not work correctly.` and its not starting any ngrok tunnel...

**Comment by philnash** [comment]
Hey @Wilson159, there have been some updates in the underlying ngrok library recently that I need to pull into this plugin. I'm working on getting an update published this week. Hopefully that will aid in getting this installed for you. I'll let you know as soon as that is available.

**Comment by philnash** [comment]
I've just published version 1.9.2. Can you try installing that and letting me know how you get on?

If it doesn't update the ngrok binary, can you open the VS Code dev tools and let me know the error that shows? Thanks!

**Comment by Wilson159** [comment]
> I've just published version 1.9.2. Can you try installing that and letting me know how you get on?
> 
> If it doesn't update the ngrok binary, can you open the VS Code dev tools and let me know the error that shows? Thanks!

Hi Phil! 

Thanks for getting back to me so fast and pushing the update, unfortunately, I'm still getting this issue... Here's the error:

`ERR spawn c:\Users\megal\.vscode\extensions\philnash.ngrok-for-vscode-1.9.2\dist\bin\ngrok.exe ENOENT: Error: spawn c:\Users\megal\.vscode\extensions\philnash.ngrok-for-vscode-1.9.2\dist\bin\ngrok.exe ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
	at onErrorNT (internal/child_process.js:465:16)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)`

**Comment by philnash** [comment]
Hi @Wilson159, sorry you're still having issues here. `ENOENT` means it can't find the file, the ngrok executable in this case, so I think something has gone wrong in the installation. Can you uninstall the extension, restart VSCode, install the extension, open the dev tools and then run a command like `ngrok start`. That should trigger downloading the executable and the error from that action should help me figure out what is going wrong.

Thank you for your help with this!

**Comment by frednaughty** [comment]
Hi @philnash, stumbled onto this GH issue while looking for a solution to the same problem. After installing ngrok for VSCode I get the same error starting a tunnel; `Can't update ngrok binary. The extension may not work correctly.`

Followed your instructions, dev tools output attached and summarized below.
```
ngrok - downloading binary https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip
ngrok - error downloading from URL RequestError: certificate has expired
```

Can confirm the URL works when copied into a web browser. 

![ngrok-for-vscode-devtools](https://user-images.githubusercontent.com/588524/151635425-b764a7d7-c7a6-4b41-9148-2a3ffac83f6f.png)

Thanks, 
Dan

**Comment by frednaughty** [comment]
@philnash, did a little more digging on this one and found an outstanding issue in VS Code that is probably to blame for this: https://github.com/microsoft/vscode/issues/136787

For anyone else experiencing this problem, can confirm changing VS Code setting `http.systemCertificates` to `false` fixed the problem. 

Extension works great, thanks Phil!

Dan

**Comment by philnash** [comment]
Thanks for digging into this @frednaughty. I'll see whether I can add this as a suggestion in the error message somehow. Or even just point to this issue for more information.

**Comment by sntgchns** [comment]
> @philnash, did a little more digging on this one and found an outstanding issue in VS Code that is probably to blame for this: [microsoft/vscode#136787](https://github.com/microsoft/vscode/issues/136787)
> 
> For anyone else experiencing this problem, changing VS Code setting `http.systemCertificates` to `false` to allow this extension to download the ngrok binaries, then changing it back fixed the problem.
> 
> Extension works great, thanks Phil!
> 
> Dan

it works! TNX

**Comment by chirag127** [comment]
@
Confirming this still hits on **Windows 11 Enterprise + corp MITM proxy** in 2026-06. Same `ERR spawn ...\ngrok.exe ENOENT` — root cause is the binary download step failing silently against the corp cert chain.

Repro on our machines:

- OS: Windows 11 Enterprise, VS Code stable
- Corp env: Zscaler-class MITM proxy, corp root CA installed in Windows cert store
- `http.systemCertificates: true` (VS Code default) — this is what actually breaks the download because Node inside VS Code then uses schannel and the ngrok CDN cert chain fails to verify through the re-signed leaf.

Workaround from #29 above (`"http.systemCertificates": false` temporarily, install extension, flip it back) still works. But it means every corp user has to know this trick, and it also disables system certs for every other extension while the toggle is off.

Suggestion for a more permanent fix:

1. Read `NODE_EXTRA_CA_CERTS` (env var most corp users already have set for npm/pnpm) and feed it into the download HTTPS agent.
2. On download failure, surface the actual error in a VS Code notification (`Failed to download ngrok binary: <error>`) instead of the silent `ENOENT` at spawn time — that would have saved everyone in this thread half a day of diagnosis.
3. Consider allowing `ngrok.executablePath` in settings so corp users can point at a pre-installed ngrok from their standard package manager (Scoop, winget, Chocolatey) and skip the extension-managed binary entirely.
@

**Comment by chirag127** [comment]
Windows corp environment additional detail: ngrok CDN (cdn.ngrok.com / bin.equinox.io) is blocked by corp proxy. The extension attempts binary download at activation with no proxy configuration option. Behind a Zscaler/BlueCoat MITM proxy, even if HTTPS_PROXY is set in the environment, the extension's download doesn't pick it up. Workaround: manually place the ngrok binary at the expected path and set the ngrok.executablePath setting. Would be good to document this and/or honor HTTPS_PROXY / NO_PROXY during binary download.
